### ISSUE TITLE
Question: is this tool able to partition data by a field? by date for example?

### ISSUE THREAD

**Issue by rubn-g** [good-lly/lowstorage#4]
**Describe the solution you'd like**
Maybe it could be a great tool to store and query log data, big amounts of data, at cheap storage price. Because we already have D1 as a database, which is cheaper to query, but at a higher storage price.

**Comment by good-lly** [comment]
To implement a feature like partitioning data by a field, you'd need to add a layer of logic on top of the existing functionality. It really depends on your implementation and requirements - Performance, speed, Cost-Effectiveness? I think it would be cool ti simplify file upload / download in lowstorage(R2) and you could possibly create architecture based on around dates and easy access to adjusted collections holding links to data ... 🤷  so, it depends ...

**Comment by good-lly** [comment]
@rubn-g wanna elaborate or may I close this?

**Comment by rubn-g** [comment]
i think we can close this, thank you very much for the info :)
